server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rntdbuat
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true